name: CI
on: [push]
jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: install packages
        run: yarn install --ignore-scripts # disable preisntall script

      - name: build
        run: yarn build
        env:
          NODE_ENV: production
          ENALBE_SERVER_CLUSTER: true
          SERVER_PORT: 8000
          ENABLE_MOCK: false
          API_GATEWAY_URL: http://localhost:8000/api

      - name: test
        run: yarn test
