name: CI
on: [push]
jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: install packages
        run: yarn install --ignore-scripts --verbose # disable preisntall script

      - name: write env file
        run: cp .env.example .env.production

      - name: build
        run: ./node_modules/.bin/next build

      - name: test
        run: yarn test --verbose
