name: CI
on: [push]
jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: install packages
        run: yarn install --ignore-scripts # disable preisntall script

      - name: wirte env file
        run: echo "NODE_ENV=production\nENALBE_SERVER_CLUSTER=true\nSERVER_PORT=8000\nENABLE_MOCK=false\nAPI_GATEWAY_URL=http://localhost:8000/api\n" > .env.production

      - name: build
        run: ./node_modules/.bin/webpack --config config/webpack.production.js --progress

      - name: test
        run: yarn test
